name: local_delivery_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #BASE
  cupertino_icons: ^1.0.5
  html: ^0.15.1
  shared_preferences: ^2.0.17
  google_fonts: ^4.0.3
  country_code_picker: ^2.0.2
  url_launcher: ^6.1.9
  url_strategy: ^0.2.0
  flutter_vector_icons: ^2.0.0
  readmore: ^2.2.0
  responsive_grid_list: ^1.3.1
  shimmer: ^2.0.0
  lottie: ^2.2.0
  file_picker: ^5.2.5
  fluttertoast: ^8.1.3

  # CURRENCY PICKER
  currency_picker: ^2.0.15

  # IMAGE
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6+1

  # TIMELINE
  timeline_tile: ^2.0.0

  # DATE TIME PICKER
  date_time_picker: ^2.1.0
  intl: ^0.18.0
  month_year_picker: ^0.2.0+3

  # CONNECTIVITY
  http: ^0.13.5
  connectivity_plus: ^3.0.3

  # STATE MANAGEMENT
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5

  #CHART
  charts_flutter: ^0.12.0
  syncfusion_flutter_charts: ^20.4.50
  flutter_switch: ^0.3.2

  # FIREBASE
  firebase_core: ^2.6.0
  firebase_messaging: ^14.2.3
  firebase_auth: ^4.2.7
  cloud_firestore: ^4.4.1
  firebase_crashlytics: ^3.0.13
  firebase_storage: ^11.0.12
  firebase_database: ^10.0.12
  paginate_firestore: ^1.0.3+1

  #NOTIFICATION
  elegant_notification: ^1.7.0

  #GOOGLE MAP
  maps_launcher: ^2.2.0

  #DOWNLOAD INVOICE PDF
  pdf: ^3.9.0
  printing: ^5.10.1
  universal_html: ^2.0.9
  path_provider: ^2.0.12

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  firebase_core_platform_interface: ^4.5.3
  intl: ^0.18.0
  cloud_firestore: ^4.4.2
  firebase_core: ^2.6.1
  cloud_firestore_web: ^3.3.2
  firebase_messaging: ^14.2.4
  firebase_core_web: ^2.2.1
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/flag/
    - assets/partener/

