name: local_delivery_admin
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # BASE
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  country_code_picker: ^3.0.0
  url_launcher: ^6.2.1
  url_strategy: ^0.2.0
  flutter_vector_icons: ^2.0.0
  readmore: ^2.2.0
  responsive_grid_list: ^1.4.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  file_picker: ^6.1.1
  fluttertoast: ^8.2.4

  # STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

  # IMAGE
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7

  # UI & CHART
  community_charts_flutter: ^1.0.4
  syncfusion_flutter_charts: ^25.1.37
  flutter_switch: ^0.3.2
  timeline_tile: ^2.0.0
  elegant_notification: ^1.11.2

  # DATE & TIME
  date_time_picker: ^3.0.0
  month_year_picker: ^0.3.0+1

  # CONNECTIVITY
  http: ^1.1.2
  connectivity_plus: ^5.0.2

  # FIREBASE (A compatible set of versions for Flutter 3.19)
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.20
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_crashlytics: ^3.4.19
  firebase_storage: ^11.6.10
  firebase_database: ^10.4.10
  paginate_firestore: ^1.0.4

  # OTHERS
  currency_picker: ^2.0.19
  maps_launcher: ^2.2.1
  pdf: ^3.10.7
  printing: ^5.11.1
  universal_html: ^2.2.4
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/flag/
    - assets/partener/
